### PR TITLE
#7 issue refact PR

### PR DESCRIPTION
**Pull request by BereGabor**
Refact the code and add unit tests, before [#7 issue](https://github.com/vifactor/repostat/issues/7) modifications.

### CODE REVIEW

**Comment by vifactor** [comment]
I am up for methods renaming to underscore_like_style, but when I check the diff of your changes, basically all files are changed because of some whitespace fix. I do not see any reason to do it.

**Comment by BereGabor** [comment]
Hi, I used pycharm reformat function what made this changes, maybe.
What is your preferred style? I could be familiar with PEP8 and java style camelCase too. 

If I resubmit the PR without style change commits, will be ok?

**Comment by vifactor** [comment]
Hi, I also use PyCharm but on Unix, so I suppose line separators there are of Unix-type. I would prefer if you keep them as is, otherwise your changes look weird. Function style change from camelCase to underscore_separated is absolutely fine and is welcome. Camel case is legacy code which I did not have will to fix.

Yes, please, resubmit your changes.

**Comment by vifactor** [comment]
Also I would prefer if you submit change "timestamp usage bug fix" as a separate PR. Do not get why timestamp is of float type, but perhaps, you are right.

**Pull request closed without merging**
