### PR TITLE
Usage documentation

### PR DESCRIPTION
**Pull request by BereGabor**
Add usage documentation.

### CODE REVIEW

**Comment by vifactor** [comment]
This change is ok, but either split it in two: the part which is related to gitstats.py script would stay here, the part for export_csv.py will go to your other pull request.

Or I will wait until the pull request with  export_csv.py is merged

**Comment by BereGabor** [comment]
To PR is OK now? 
Thanks you reviews and help. Ï learned a lot.

**Comment by vifactor** [comment]
The PR looks fine, I am just away from my computer for several days, so if you do not mind I will merge it later.
Thanks for contributing!

**Comment by vifactor** [comment]
@BereGabor, I cannot rebase and do not want to create a merge commit for such a simple one-commit PR. Would you be so kind to cherry-pick the commit on the most up-to-date master and resubmit PR?

**Pull request closed without merging**
